import { CurriculumLevel, CurriculumSegment } from './types';

// Organized curriculum with segments
export const CURRICULUM_SEGMENTS: CurriculumSegment[] = [
  {
    id: 'pitch',
    name: 'Pitch',
    description: 'Develop fundamental pitch recognition and scale degree awareness',
    icon: '🎵',
    color: 'purple',
    levels: [
      {
        id: 'scale_degree_major_1',
        name: 'Major Scale Degrees 1-3-5',
        type: 'scale_degree',
        items: ['1', '3', '5'],
        context: 'major',
        unlockRequirement: 80,
        description: 'Identify the tonic triad notes (1, 3, 5) in a major scale',
        segmentId: 'pitch',
      },
      {
        id: 'scale_degree_major_2',
        name: 'Major Scale Degrees 1-5',
        type: 'scale_degree',
        items: ['1', '2', '3', '4', '5'],
        context: 'major',
        unlockRequirement: 75,
        description: 'Identify scale degrees 1-5 in a major scale',
        segmentId: 'pitch',
      },
      {
        id: 'scale_degree_major_full',
        name: 'All Major Scale Degrees',
        type: 'scale_degree',
        items: ['1', '2', '3', '4', '5', '6', '7'],
        context: 'major',
        unlockRequirement: 75,
        description: 'Identify all 7 scale degrees in a major scale',
        segmentId: 'pitch',
      },
      {
        id: 'scale_degree_minor',
        name: 'Natural Minor Scale Degrees',
        type: 'scale_degree',
        items: ['1', '2', '3', '4', '5', '6', '7'],
        context: 'natural_minor',
        unlockRequirement: 75,
        description: 'Identify all 7 scale degrees in natural minor',
        segmentId: 'pitch',
      },
      {
        id: 'level_1',
        name: 'Tonic Major vs Minor Thirds',
        type: 'interval',
        items: ['minor_3rd', 'major_3rd'],
        scaleDegrees: [0],
        unlockRequirement: 80,
        description: 'Learn major and minor thirds from the root note',
        segmentId: 'pitch',
      },
      {
        id: 'level_2',
        name: 'Dominant Major vs Minor Thirds',
        type: 'interval',
        items: ['minor_3rd', 'major_3rd'],
        scaleDegrees: [4],
        unlockRequirement: 80,
        description: 'Practice thirds from the 5th scale degree',
        segmentId: 'pitch',
      },
      {
        id: 'level_3',
        name: 'All Thirds in Scale',
        type: 'interval',
        items: ['minor_3rd', 'major_3rd'],
        unlockRequirement: 75,
        description: 'Identify thirds from any scale degree',
        segmentId: 'pitch',
      },
      {
        id: 'scale_degree_major_triads',
        name: 'Major Scale Triads (Harmonic)',
        type: 'scale_degree',
        items: ['1', '2', '3', '4', '5', '6', '7'],
        context: 'major_triads',
        unlockRequirement: 70,
        description: 'Identify triads built on each scale degree in major',
        segmentId: 'pitch',
      },
      {
        id: 'scale_degree_minor_triads',
        name: 'Minor Scale Triads (Harmonic)',
        type: 'scale_degree',
        items: ['1', '2', '3', '4', '5', '6', '7'],
        context: 'minor_triads',
        unlockRequirement: 70,
        description: 'Identify triads built on each scale degree in minor',
        segmentId: 'pitch',
      },
      {
        id: 'scale_degree_major_7ths',
        name: 'Major Scale 7th Chords',
        type: 'scale_degree',
        items: ['1', '2', '3', '4', '5', '6', '7'],
        context: 'major_7ths',
        unlockRequirement: 70,
        description: 'Identify 7th chords built on each scale degree in major',
        segmentId: 'pitch',
      },
      {
        id: 'scale_degree_minor_7ths',
        name: 'Minor Scale 7th Chords',
        type: 'scale_degree',
        items: ['1', '2', '3', '4', '5', '6', '7'],
        context: 'minor_7ths',
        unlockRequirement: 70,
        description: 'Identify 7th chords built on each scale degree in minor',
        segmentId: 'pitch',
      },
      {
        id: 'level_4',
        name: 'Tonic Triads (I and vi)',
        type: 'triad',
        items: ['major', 'minor'],
        scaleDegrees: [0, 5],
        unlockRequirement: 80,
        description: 'Learn the tonic major chord and its relative minor',
        segmentId: 'pitch',
      },
      {
        id: 'level_5',
        name: 'Dominant Triads (V)',
        type: 'triad',
        items: ['major'],
        scaleDegrees: [4],
        unlockRequirement: 85,
        description: 'Master the dominant chord',
        segmentId: 'pitch',
      },
      {
        id: 'level_6',
        name: 'All Diatonic Triads',
        type: 'triad',
        items: ['major', 'minor', 'diminished'],
        unlockRequirement: 75,
        description: 'Identify all triads in the major scale',
        segmentId: 'pitch',
      },
      {
        id: 'level_7',
        name: 'Common Seventh Chords',
        type: 'seventh_chord',
        items: ['major_7', 'minor_7', 'dominant_7'],
        unlockRequirement: 75,
        description: 'Learn the most common seventh chords',
        segmentId: 'pitch',
      },
      {
        id: 'level_8',
        name: 'Advanced Seventh Chords',
        type: 'seventh_chord',
        items: ['major_7', 'minor_7', 'dominant_7', 'half_diminished_7', 'diminished_7', 'minor_major_7'],
        unlockRequirement: 70,
        description: 'Master all seventh chord qualities',
        segmentId: 'pitch',
      },
      {
        id: 'level_9',
        name: 'Major vs Minor Modes',
        type: 'mode',
        items: ['ionian', 'lydian', 'mixolydian', 'aeolian', 'dorian'],
        unlockRequirement: 70,
        description: 'Distinguish between major and minor modes',
        segmentId: 'pitch',
      },
      {
        id: 'level_10',
        name: 'All Modes',
        type: 'mode',
        items: ['ionian', 'dorian', 'phrygian', 'lydian', 'mixolydian', 'aeolian', 'locrian'],
        unlockRequirement: 70,
        description: 'Master all seven modes',
        segmentId: 'pitch',
      },
    ],
  },
  // Intervals - Comprehensive interval training
  {
    id: 'intervals',
    name: 'Intervals',
    description: 'Master all intervals in harmonic and melodic contexts',
    icon: '📏',
    color: 'green',
    levels: [
      // Perfect Fourths and Fifths (easiest - start here)
      {
        id: 'int_harmonic_4ths_5ths',
        name: 'Harmonic: Fourths and Fifths',
        type: 'interval',
        items: ['perfect_4th', 'perfect_5th'],
        intervalPresentation: 'harmonic',
        unlockRequirement: 75,
        description: 'Recognize perfect 4ths and 5ths played together',
        segmentId: 'intervals',
      },
      {
        id: 'int_melodic_4ths_5ths_asc',
        name: 'Melodic: Fourths and Fifths (Ascending)',
        type: 'interval',
        items: ['perfect_4th', 'perfect_5th'],
        intervalPresentation: 'melodic',
        intervalDirection: 'ascending',
        unlockRequirement: 75,
        description: 'Identify ascending perfect 4ths and 5ths',
        segmentId: 'intervals',
      },
      {
        id: 'int_melodic_4ths_5ths_desc',
        name: 'Melodic: Fourths and Fifths (Descending)',
        type: 'interval',
        items: ['perfect_4th', 'perfect_5th'],
        intervalPresentation: 'melodic',
        intervalDirection: 'descending',
        unlockRequirement: 75,
        description: 'Identify descending perfect 4ths and 5ths',
        segmentId: 'intervals',
      },
      
      // Thirds
      {
        id: 'int_harmonic_3rds',
        name: 'Harmonic: Thirds',
        type: 'interval',
        items: ['minor_3rd', 'major_3rd'],
        intervalPresentation: 'harmonic',
        unlockRequirement: 75,
        description: 'Distinguish major and minor 3rds played together',
        segmentId: 'intervals',
      },
      {
        id: 'int_melodic_3rds_asc',
        name: 'Melodic: Thirds (Ascending)',
        type: 'interval',
        items: ['minor_3rd', 'major_3rd'],
        intervalPresentation: 'melodic',
        intervalDirection: 'ascending',
        unlockRequirement: 75,
        description: 'Identify ascending major and minor 3rds',
        segmentId: 'intervals',
      },
      {
        id: 'int_melodic_3rds_desc',
        name: 'Melodic: Thirds (Descending)',
        type: 'interval',
        items: ['minor_3rd', 'major_3rd'],
        intervalPresentation: 'melodic',
        intervalDirection: 'descending',
        unlockRequirement: 75,
        description: 'Identify descending major and minor 3rds',
        segmentId: 'intervals',
      },
      
      // Sixths
      {
        id: 'int_harmonic_6ths',
        name: 'Harmonic: Sixths',
        type: 'interval',
        items: ['minor_6th', 'major_6th'],
        intervalPresentation: 'harmonic',
        unlockRequirement: 75,
        description: 'Recognize major and minor 6ths played together',
        segmentId: 'intervals',
      },
      {
        id: 'int_melodic_6ths_asc',
        name: 'Melodic: Sixths (Ascending)',
        type: 'interval',
        items: ['minor_6th', 'major_6th'],
        intervalPresentation: 'melodic',
        intervalDirection: 'ascending',
        unlockRequirement: 75,
        description: 'Identify ascending major and minor 6ths',
        segmentId: 'intervals',
      },
      {
        id: 'int_melodic_6ths_desc',
        name: 'Melodic: Sixths (Descending)',
        type: 'interval',
        items: ['minor_6th', 'major_6th'],
        intervalPresentation: 'melodic',
        intervalDirection: 'descending',
        unlockRequirement: 75,
        description: 'Identify descending major and minor 6ths',
        segmentId: 'intervals',
      },
      
      // Seconds (more challenging)
      {
        id: 'int_harmonic_2nds',
        name: 'Harmonic: Seconds',
        type: 'interval',
        items: ['minor_2nd', 'major_2nd'],
        intervalPresentation: 'harmonic',
        unlockRequirement: 75,
        description: 'Distinguish major and minor 2nds played together',
        segmentId: 'intervals',
      },
      {
        id: 'int_melodic_2nds_asc',
        name: 'Melodic: Seconds (Ascending)',
        type: 'interval',
        items: ['minor_2nd', 'major_2nd'],
        intervalPresentation: 'melodic',
        intervalDirection: 'ascending',
        unlockRequirement: 75,
        description: 'Identify ascending half steps and whole steps',
        segmentId: 'intervals',
      },
      {
        id: 'int_melodic_2nds_desc',
        name: 'Melodic: Seconds (Descending)',
        type: 'interval',
        items: ['minor_2nd', 'major_2nd'],
        intervalPresentation: 'melodic',
        intervalDirection: 'descending',
        unlockRequirement: 75,
        description: 'Identify descending half steps and whole steps',
        segmentId: 'intervals',
      },
      
      // Sevenths
      {
        id: 'int_harmonic_7ths',
        name: 'Harmonic: Sevenths',
        type: 'interval',
        items: ['minor_7th', 'major_7th'],
        intervalPresentation: 'harmonic',
        unlockRequirement: 75,
        description: 'Recognize major and minor 7ths played together',
        segmentId: 'intervals',
      },
      {
        id: 'int_melodic_7ths_asc',
        name: 'Melodic: Sevenths (Ascending)',
        type: 'interval',
        items: ['minor_7th', 'major_7th'],
        intervalPresentation: 'melodic',
        intervalDirection: 'ascending',
        unlockRequirement: 75,
        description: 'Identify ascending major and minor 7ths',
        segmentId: 'intervals',
      },
      {
        id: 'int_melodic_7ths_desc',
        name: 'Melodic: Sevenths (Descending)',
        type: 'interval',
        items: ['minor_7th', 'major_7th'],
        intervalPresentation: 'melodic',
        intervalDirection: 'descending',
        unlockRequirement: 75,
        description: 'Identify descending major and minor 7ths',
        segmentId: 'intervals',
      },
      
      // Tritones and Major Sevenths (challenging)
      {
        id: 'int_harmonic_tritone_maj7',
        name: 'Harmonic: Tritones and Major Sevenths',
        type: 'interval',
        items: ['tritone', 'major_7th'],
        intervalPresentation: 'harmonic',
        unlockRequirement: 70,
        description: 'Distinguish tritones from major 7ths harmonically',
        segmentId: 'intervals',
      },
      {
        id: 'int_melodic_tritone_maj7_asc',
        name: 'Melodic: Tritones and Major Sevenths (Ascending)',
        type: 'interval',
        items: ['tritone', 'major_7th'],
        intervalPresentation: 'melodic',
        intervalDirection: 'ascending',
        unlockRequirement: 70,
        description: 'Identify ascending tritones vs major 7ths',
        segmentId: 'intervals',
      },
      {
        id: 'int_melodic_tritone_maj7_desc',
        name: 'Melodic: Tritones and Major Sevenths (Descending)',
        type: 'interval',
        items: ['tritone', 'major_7th'],
        intervalPresentation: 'melodic',
        intervalDirection: 'descending',
        unlockRequirement: 70,
        description: 'Identify descending tritones vs major 7ths',
        segmentId: 'intervals',
      },
      
      // All Intervals - Comprehensive
      {
        id: 'int_all_harmonic',
        name: 'All Intervals: Harmonic',
        type: 'interval',
        items: ['minor_2nd', 'major_2nd', 'minor_3rd', 'major_3rd', 'perfect_4th', 'tritone', 'perfect_5th', 'minor_6th', 'major_6th', 'minor_7th', 'major_7th', 'octave'],
        intervalPresentation: 'harmonic',
        unlockRequirement: 70,
        description: 'Master all intervals played harmonically',
        segmentId: 'intervals',
      },
      {
        id: 'int_all_melodic_asc',
        name: 'All Intervals: Melodic (Ascending)',
        type: 'interval',
        items: ['minor_2nd', 'major_2nd', 'minor_3rd', 'major_3rd', 'perfect_4th', 'tritone', 'perfect_5th', 'minor_6th', 'major_6th', 'minor_7th', 'major_7th', 'octave'],
        intervalPresentation: 'melodic',
        intervalDirection: 'ascending',
        unlockRequirement: 70,
        description: 'Master all ascending intervals',
        segmentId: 'intervals',
      },
      {
        id: 'int_all_melodic_desc',
        name: 'All Intervals: Melodic (Descending)',
        type: 'interval',
        items: ['minor_2nd', 'major_2nd', 'minor_3rd', 'major_3rd', 'perfect_4th', 'tritone', 'perfect_5th', 'minor_6th', 'major_6th', 'minor_7th', 'major_7th', 'octave'],
        intervalPresentation: 'melodic',
        intervalDirection: 'descending',
        unlockRequirement: 70,
        description: 'Master all descending intervals',
        segmentId: 'intervals',
      },
    ],
  },
  {
    id: 'triads',
    name: 'Triads',
    description: 'Three-note chord structures and inversions',
    icon: '🔺',
    color: 'yellow',
    levels: [],
  },
  {
    id: 'sevenths',
    name: 'Sevenths',
    description: 'Four-note seventh chord voicings',
    icon: '7️⃣',
    color: 'red',
    levels: [],
  },
  {
    id: 'tonal_progressions',
    name: 'Tonal Progressions',
    description: 'Common chord progressions in tonal music',
    icon: '🎼',
    color: 'blue',
    levels: [],
  },
  {
    id: 'secondary_chords',
    name: 'Secondary Chords',
    description: 'Secondary dominants and borrowed chords',
    icon: '🔄',
    color: 'indigo',
    levels: [],
  },
  {
    id: 'extended_chords',
    name: 'Extended Chords',
    description: '9th, 11th, and 13th chord extensions',
    icon: '🎹',
    color: 'violet',
    levels: [],
  },
  {
    id: 'rhythm',
    name: 'Rhythm',
    description: 'Rhythmic patterns and timing',
    icon: '🥁',
    color: 'orange',
    levels: [],
  },
  {
    id: 'scales',
    name: 'Scales',
    description: 'Exotic and non-diatonic scale systems',
    icon: '🎶',
    color: 'pink',
    levels: [],
  },
  {
    id: 'modal_voicings',
    name: 'Modal Voicings',
    description: 'Modal chord voicings and colors',
    icon: '🌈',
    color: 'cyan',
    levels: [],
  },
  {
    id: 'melodic_dictation',
    name: 'Melodic Dictation',
    description: 'Transcribe melodies by ear',
    icon: '✍️',
    color: 'teal',
    levels: [],
  },
  {
    id: 'modal_harmony',
    name: 'Modal Harmony',
    description: 'Harmonic concepts in modal contexts',
    icon: '🎭',
    color: 'emerald',
    levels: [],
  },
  {
    id: 'bitonal_harmony',
    name: 'Bitonal Harmony',
    description: 'Two keys simultaneously',
    icon: '🎪',
    color: 'lime',
    levels: [],
  },
  {
    id: 'reharmonization',
    name: 'Reharmonization',
    description: 'Alternative harmonic approaches',
    icon: '🔀',
    color: 'amber',
    levels: [],
  },
  {
    id: 'polyrhythm',
    name: 'Polyrhythm',
    description: 'Multiple rhythms simultaneously',
    icon: '🎵🎶',
    color: 'rose',
    levels: [],
  },
  {
    id: 'odd_meter',
    name: 'Odd Meter',
    description: 'Time signatures beyond 4/4',
    icon: '⏱️',
    color: 'fuchsia',
    levels: [],
  },
  {
    id: 'polychords',
    name: 'Polychords',
    description: 'Multiple chords stacked together',
    icon: '🏗️',
    color: 'sky',
    levels: [],
  },
  {
    id: 'twelve_tone',
    name: 'Twelve Tone Harmony',
    description: 'Serialist and twelve-tone techniques',
    icon: '🎲',
    color: 'slate',
    levels: [],
  },
  {
    id: 'inner_note_hearing',
    name: 'Inner Note Hearing',
    description: 'Identify inner voices in complex textures',
    icon: '🔍',
    color: 'zinc',
    levels: [],
  },
  {
    id: 'clusters',
    name: 'Clusters',
    description: 'Dense chromatic chord clusters',
    icon: '💥',
    color: 'stone',
    levels: [],
  },
];

// Flatten all levels from segments for backwards compatibility
export const CURRICULUM: CurriculumLevel[] = CURRICULUM_SEGMENTS.flatMap(segment => segment.levels);

export function getCurrentLevel(completedLevels: string[]): CurriculumLevel {
  const nextLevel = CURRICULUM.find(level => !completedLevels.includes(level.id));
  return nextLevel || CURRICULUM[CURRICULUM.length - 1];
}

export function canUnlockNextLevel(currentLevelId: string, accuracy: number): boolean {
  const currentLevel = CURRICULUM.find(level => level.id === currentLevelId);
  if (!currentLevel) return false;
  return accuracy >= currentLevel.unlockRequirement;
}

export function getDisplayName(item: string): string {
  // Convert snake_case to Title Case
  return item
    .split('_')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}
